### ISSUE TITLE
Url check is failing

### ISSUE THREAD

**Issue by sebamarynissen** [sebamarynissen/simtropolis-channel#1]
Apparently the url-check action is failing because `PREVIOUS_COMMIT` is not defined. This variable [is read from](https://github.com/memo33/sc4pac-actions/blob/main/actions/url-check/action.yaml) `${github.event.before}`, so the reason is probably that with our current flow of running the deploy workflow manually, this doesn't work somehow.

**Comment by memo33** [comment]
Yeah, this part of the action is [not perfect](https://github.com/memo33/sc4pac-actions/blob/9893a7b2b4c83afcc126ecdfe2ee7d4ac9e5584c/actions/url-check/action.yaml#L65) yet, as sometimes the `github.event.before` is not set. I guess you triggered the workflow via `workflow_dispatch`? Alternatively, you could trigger it via `push` or by "Rerun all jobs" for a failed action in the Actions tab.

**Comment by sebamarynissen** [comment]
I have two ways to trigger it currently:

```yaml
on:
  workflow_dispatch: # Allow triggering manually
  workflow_run:
    workflows:
      - Fetch Simtropolis package
    types:
      - completed
```

The `workflow_run` was needed because commits by the GitHub actions bot would not trigger the deploy action if it just had
```yaml
on:
  push:
    branches: [ "main" ]
```
set. That's because GitHub wants to avoid infinite loops of actions retriggering themselves apparently.
