### ISSUE TITLE
Improve fetch/lint/deploy workflow

### ISSUE THREAD

**Issue by sebamarynissen** [sebamarynissen/simtropolis-channel#12]
@memo33 I'm currently struggling with the actions. I have managed to automatically create a PR for every package that gets added, but the problem is that the lint action won't run on that PR, because GitHub refuses to run actions on commits made by a bot.

I've already tried committing with my own identity (through a PAT) instead of using the github-bot token, but to no avail. Do you have any experience with this?

I'm now trying another approach where I manually trigger the lint workflow, let's see if that works, but it feels hacky.

**Comment by sebamarynissen** [comment]
There might be a way to do this with [GitHub Apps](https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/about-creating-github-apps) apparently. I'm going to experiment with it.

**Comment by memo33** [comment]
I'm not too experienced with this, unfortunately. Though, in your triggering `fetch` workflow, couldn't you just add a second job that is executed after the first one completes? This would ensure that everything runs as part of the same event trigger. Something like:
```yaml
jobs:
  add-from-simtropolis:
    …

  deploy:
    needs: add-from-simtropolis
    uses: memo33/sc4pac-actions/.github/workflows/sc4pac-channel.yaml@main
    with:
      …
```

Calling the `lint` action directly should be fine as well. Just make sure to define the input parameter (not sure why it doesn't seem to error out for you):
```yaml
      uses: memo33/sc4pac-actions/actions/lint@main
      with:
        path: src/yaml
```
Inlining the deploy job would be more complicated and I'd avoid it if possible. Though, maybe I could refactor it so you could call just that job if necessary.
